@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package mod.traister101.test;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;